[project]
name = "leethack"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
    "django>=5.2.1",
    "django-environ>=0.12.0",
    "psycopg2>=2.9.10",
]
