# Generated by Django 5.2.1 on 2025-06-06 05:47

import leethack.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_background",
            field=models.ImageField(
                blank=True,
                default="profile_backgrounds/default.jpg",
                upload_to=leethack.users.models.upload_profile_background,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/default.jpg",
                upload_to=leethack.users.models.upload_profile_picture,
            ),
        ),
    ]
