# Generated by Django 5.2.1 on 2025-05-30 20:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of category.", max_length=255, unique=True
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Hackathon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of hackathon.", max_length=255),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of hackathon."),
                ),
                (
                    "prize",
                    models.PositiveIntegerField(
                        help_text="Prize for winning hackathon."
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(help_text="Start date and time of hackathon."),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(help_text="End date and time of hackathon."),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category of hackathon.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hackathons.category",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        help_text="Organizer of hackathon.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_hackathons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("start_datetime__lt", models.F("end_datetime"))
                        ),
                        name="end_datetime_after_start_datetime",
                    )
                ],
            },
        ),
    ]
