# Generated by Django 5.2.1 on 2025-05-30 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0001_initial"),
        ("participations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_hackathons",
                to="participations.participant",
            ),
        ),
    ]
