# Generated by Django 5.2.1 on 2025-06-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0002_hackathon_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="hackathons/"),
        ),
    ]
