# Generated by Django 5.2.1 on 2025-06-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0003_hackathon_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="image",
            field=models.ImageField(upload_to="hackathons/"),
        ),
    ]
