# Generated by Django 5.2.1 on 2025-06-06 05:39

import leethack.hackathons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0004_alter_hackathon_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="image",
            field=models.ImageField(
                upload_to=leethack.hackathons.models.upload_hackathon_image
            ),
        ),
    ]
