# Generated by Django 5.2.1 on 2025-05-30 20:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hackathons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "hackathon",
                    models.ForeignKey(
                        help_text="Hackathon this user is participant of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="hackathons.hackathon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who is participant",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "hackathon"),
                        name="unique_participant_user_hackathon",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ParticipationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("pending", "Pending"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Status of request.",
                        max_length=15,
                    ),
                ),
                (
                    "hackathon",
                    models.ForeignKey(
                        help_text="Hackathon this user is participant of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participation_requests",
                        to="hackathons.hackathon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who sent request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "hackathon"),
                        name="unique_participation_request_user_hackathon",
                    )
                ],
            },
        ),
    ]
