# Generated by Django 5.2.1 on 2025-06-01 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0002_hackathon_winner"),
        ("participations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="participationrequest",
            name="unique_participation_request_user_hackathon",
        ),
        migrations.AddConstraint(
            model_name="participationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "approved")),
                fields=("user", "hackathon"),
                name="unique_participation_request_user_hackathon",
            ),
        ),
    ]
